# -*- coding: utf-8 -*-
# Generated by Django 2.2.5 on 2019-09-13 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='list name')),
            ],
        ),
        migrations.CreateModel(
            name='TodoItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('todo_list',
                 models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.TodoListModel')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('todo_list', 'text')},
            },
        ),
    ]
