# Generated by Django 2.2.5 on 2019-09-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmodel',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='list name'),
        ),
    ]
