# Generated by Django 2.2.5 on 2019-09-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('todo', '0003_auto_20190913_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitemmodel',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
